FROM maven:3.9.6-amazoncorretto-21-debian as build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

FROM amazoncorretto:21-alpine

WORKDIR /app

COPY --from=build /app/target/Tayarim-0.0.1-SNAPSHOT.jar .

CMD ["java", "-jar", "Tayarim-0.0.1-SNAPSHOT.jar"]