FROM maven:3.9.6-amazoncorretto-21-debian as build

WORKDIR /app

COPY pom.xml .
COPY src ./src
COPY .env.production .

RUN --mount=type=secret,id=USER \
    sed -i "s/USER=/USER=$(cat /run/secrets/USER)/" .env.production

RUN --mount=type=secret,id=PASSWORD \
    sed -i "s/PASSWORD=/PASSWORD=$(cat /run/secrets/PASSWORD)/" .env.production

RUN --mount=type=secret,id=STRIPE_SECRET_KEY \
    sed -i "s/STRIPE_SECRET_KEY=/STRIPE_SECRET_KEY=$(cat /run/secrets/STRIPE_SECRET_KEY)/" .env.production

RUN --mount=type=secret,id=GCP \
    sed -i "s/GCP=/GCP=$(cat /run/secrets/GCP)/" .env.production

RUN --mount=type=secret,id=PRIVATE_KEY \
    sed -i "s/PRIVATE_KEY=/PRIVATE_KEY=$(cat /run/secrets/PRIVATE_KEY)/" .env.production

RUN mvn clean package -DskipTests

FROM amazoncorretto:21-alpine

WORKDIR /app

COPY --from=build /app/target/Tayarim-0.0.1-SNAPSHOT.jar .

CMD ["java", "-jar", "Tayarim-0.0.1-SNAPSHOT.jar"]