INSERT INTO UTILISATEUR (NOM, PRENOM, EMAIL, NUMTEL, MOTDEPASSE) VALUES ('John', 'Doe', 'johndoe@gmail.com', '+330612345678', '$2a$12$3hQDUblvPShmuQg/.g0Qk.wHAGjqPL54RMO/lNgsei/HQGo0ZLIYm');
INSERT INTO PROPRIETAIRE (IDUSER, DATEINSCRIPTION, ISPASSWORDUPDATED, COMMISSION) VALUES ((SELECT max(ID) FROM UTILISATEUR), CURRENT_TIME(), TRUE, 20.00);
INSERT INTO ICONE (SVG) VALUES ( 'lien vers svg' );
INSERT INTO TYPELOGEMENT (NOM, IDICONE) VALUES ( 'Appartement', (SELECT max(ID) FROM UTILISATEUR) );
INSERT INTO LOGEMENT (TITRE, LOUABLE, NOMBRESDECHAMBRES, NOMBRESDELITS, NOMBRESSALLESDEBAINS, CAPACITEMAXPERSONNE, NOMBRESNUITSMIN, DESCRIPTION, NOTE, PRIXPARNUIT, DEFAULTCHECKIN, DEFAULTCHECKOUT, INTERVALRESERVATION, VILLE, ADRESSE, CODEPOSTAL, PAYS, ETAGE, NUMERODEPORTE, LONGITUDE, LATITUDE, IDTYPELOGEMENT, IDPROPRIETAIRE) VALUES ( 'Jolie petit endroit', true, 1, 1, 1, 1, 6, 'une description', 2.5, 25.30, CURRENT_TIME(), CURRENT_TIME(), 1, 'Etampes', '85 rue de la république', '91150', 'France', '1', '1', 48.43397, 2.16577, 1, (SELECT max(ID) FROM UTILISATEUR));

INSERT INTO UTILISATEUR (NOM, PRENOM, EMAIL, NUMTEL, MOTDEPASSE) VALUES ('Jean', 'Paul', 'jeanpaul@gmail.com', '+330623456789', '$2a$12$3hQDUblvPShmuQg/.g0Qk.wHAGjqPL54RMO/lNgsei/HQGo0ZLIYm');
INSERT INTO PROPRIETAIRE (IDUSER, DATEINSCRIPTION, ISPASSWORDUPDATED, COMMISSION) VALUES ((SELECT max(ID) FROM UTILISATEUR), CURRENT_TIME(), TRUE, 20.00);

INSERT INTO UTILISATEUR (NOM, PRENOM, EMAIL, NUMTEL, MOTDEPASSE) VALUES ('Jade', 'Min', 'jadmin@gmail.com', '+330634567890', '$2a$12$3hQDUblvPShmuQg/.g0Qk.wHAGjqPL54RMO/lNgsei/HQGo0ZLIYm');
INSERT INTO ADMINISTRATEUR (IDUSER) VALUES ((SELECT max(ID) FROM UTILISATEUR));

INSERT INTO UTILISATEUR (NOM, PRENOM, EMAIL, NUMTEL, MOTDEPASSE) VALUES ('Ilad', 'Min', 'jiladmin@gmail.com', '+330634567891', '$2a$12$3hQDUblvPShmuQg/.g0Qk.wHAGjqPL54RMO/lNgsei/HQGo0ZLIYm');
INSERT INTO ADMINISTRATEUR (IDUSER) VALUES ((SELECT max(ID) FROM UTILISATEUR));