DROP TABLE IF EXISTS NOTIFICATION;
DROP TABLE IF EXISTS FACTURE;
DROP TABLE IF EXISTS CONTENIR;
DROP TABLE IF EXISTS RESPECTER;
DROP TABLE IF EXISTS INDISPONIBILITE;
DROP TABLE IF EXISTS AVIS;
DROP TABLE IF EXISTS IMAGELOGEMENT;
DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS DEPENSE;
DROP TABLE IF EXISTS LOGEMENT;
DROP TABLE IF EXISTS TYPELOGEMENT;
DROP TABLE IF EXISTS AMENAGEMENT;
DROP TABLE IF EXISTS REGLESLOGEMENT;
DROP TABLE IF EXISTS IC0NE;
DROP TABLE IF EXISTS CATEGORIEAMENAGEMENT;
DROP TABLE IF EXISTS ADMINISTRATEUR;
DROP TABLE IF EXISTS PROPRIETAIRE;
DROP TABLE IF EXISTS UTILISATEUR;

CREATE TABLE IF NOT EXISTS UTILISATEUR
(
    ID         INT PRIMARY KEY AUTO_INCREMENT,
    NOM        VARCHAR(100),
    PRENOM     VARCHAR(100),
    EMAIL      VARCHAR(100),
    NUMTEL     VARCHAR(100),
    MOTDEPASSE VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS PROPRIETAIRE
(
    IDUSER            INT PRIMARY KEY,
    ADRESSE           VARCHAR(300),
    DATEINSCRIPTION   DATETIME,
    ISPASSWORDUPDATED BOOLEAN,
    COMMISSION        FLOAT,
    ISVALIDATED       BOOLEAN
);

CREATE TABLE IF NOT EXISTS ADMINISTRATEUR
(
    IDUSER INT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS LOGEMENT
(
    ID                   INT PRIMARY KEY AUTO_INCREMENT,
    TITRE                VARCHAR(100),
    ISLOUABLE            BOOL,
    NOMBRESDECHAMBRES    INT,
    NOMBRESDELITS        INT,
    NOMBRESSALLESDEBAINS INT,
    CAPACITEMAXPERSONNE  INT,
    NOMBRESNUITSMIN      INT,
    DESCRIPTION          VARCHAR(500),
    NOTE                 FLOAT,
    PRIXPARNUIT          FLOAT,
    DEFAULTCHECKIN       TIME,
    DEFAULTCHECKOUT      TIME,
    INTERVALRESERVATION  INT,
    VILLE                VARCHAR(30),
    ADRESSE              VARCHAR(150),
    CODEPOSTAL           VARCHAR(10),
    PAYS                 VARCHAR(30),
    ETAGE                VARCHAR(30),
    NUMERODEPORTE        VARCHAR(30),
    IDTYPELOGEMENT       INT,
    IDPROPRIETAIRE       INT
);

CREATE TABLE IF NOT EXISTS TYPELOGEMENT
(
    ID    INT PRIMARY KEY AUTO_INCREMENT,
    NOM   VARCHAR(100),
    ICONE VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS RESERVATION
(
    ID              INT PRIMARY KEY AUTO_INCREMENT,
    IDCOMMANDE      VARCHAR(100),
    STATUT          VARCHAR(100),
    EMAIL           VARCHAR(100),
    NUMTEL          VARCHAR(100),
    NOM             VARCHAR(100),
    PRENOM          VARCHAR(100),
    NBPERSONNES     INT,
    MONTANT         FLOAT,
    CHECKIN         TIME,
    CHECKOUT        TIME,
    DATEARRIVEE     DATE,
    DATEDEPART      DATE,
    IDLOGEMENT      INT,
    DATERESERVATION DATETIME,
    PAYMENTINTENT   VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS AMENAGEMENT
(
    ID                     INT PRIMARY KEY AUTO_INCREMENT,
    NOM                    VARCHAR(100),
    ICONE                  VARCHAR(1000),
    IDCATEGORIEAMENAGEMENT INT
);

CREATE TABLE IF NOT EXISTS CATEGORIEAMENAGEMENT
(
    ID  INT PRIMARY KEY AUTO_INCREMENT,
    NOM VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS DEPENSE
(
    ID         INT PRIMARY KEY AUTO_INCREMENT,
    LIBELLE    VARCHAR(200),
    PRIX       FLOAT,
    DATE       DATE,
    IDLOGEMENT INT
);

CREATE TABLE IF NOT EXISTS ICONE
(
    ID  INT PRIMARY KEY AUTO_INCREMENT,
    SVG VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS REGLESLOGEMENT
(
    ID    INT PRIMARY KEY AUTO_INCREMENT,
    NOM   VARCHAR(100),
    ICONE VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS IMAGELOGEMENT
(
    ID          INT PRIMARY KEY AUTO_INCREMENT,
    URL         VARCHAR(1000),
    IDLOGEMENT  INT,
    ISMAINIMAGE BOOLEAN
);

CREATE TABLE IF NOT EXISTS AVIS
(
    ID         INT PRIMARY KEY AUTO_INCREMENT,
    TEXTE      VARCHAR(100),
    PSEUDO     VARCHAR(100),
    NOTE       INT,
    DATE       DATETIME,
    IDLOGEMENT INT
);

CREATE TABLE IF NOT EXISTS INDISPONIBILITE
(
    ID         INT PRIMARY KEY AUTO_INCREMENT,
    DATEDEBUT  DATE,
    DATEFIN    DATE,
    IDLOGEMENT INT
);

CREATE TABLE IF NOT EXISTS RESPECTER
(
    IDLOGEMENT       INT,
    IDREGLESLOGEMENT INT,
    PRIMARY KEY (IDLOGEMENT, IDREGLESLOGEMENT)
);

CREATE TABLE IF NOT EXISTS CONTENIR
(
    IDLOGEMENT    INT,
    IDAMENAGEMENT INT,
    PRIMARY KEY (IDLOGEMENT, IDAMENAGEMENT)
);

CREATE TABLE IF NOT EXISTS NOTIFICATION
(
    ID      INT PRIMARY KEY AUTO_INCREMENT,
    MESSAGE VARCHAR(100),
    DATE    DATETIME,
    IDUSER  INT,
    TYPE    VARCHAR(100),
    ISREAD  BOOLEAN
);

CREATE TABLE IF NOT EXISTS FACTURE
(
    ID             INT PRIMARY KEY AUTO_INCREMENT,
    NUMEROFACTURE  VARCHAR(100),
    DATE           DATE,
    MONTANT        FLOAT,
    URL            VARCHAR(1000),
    IDPROPRIETAIRE INT
);

ALTER TABLE PROPRIETAIRE
    ADD FOREIGN KEY (IDUSER) REFERENCES UTILISATEUR (ID);

ALTER TABLE ADMINISTRATEUR
    ADD FOREIGN KEY (IDUSER) REFERENCES UTILISATEUR (ID);

ALTER TABLE LOGEMENT
    ADD FOREIGN KEY (IDTYPELOGEMENT) REFERENCES TYPELOGEMENT (ID);

ALTER TABLE LOGEMENT
    ADD FOREIGN KEY (IDPROPRIETAIRE) REFERENCES PROPRIETAIRE (IDUSER);

ALTER TABLE RESERVATION
    ADD FOREIGN KEY (IDLOGEMENT) REFERENCES LOGEMENT (ID);

ALTER TABLE AMENAGEMENT
    ADD FOREIGN KEY (IDCATEGORIEAMENAGEMENT) REFERENCES CATEGORIEAMENAGEMENT (ID);

ALTER TABLE DEPENSE
    ADD FOREIGN KEY (IDLOGEMENT) REFERENCES LOGEMENT (ID);

ALTER TABLE IMAGELOGEMENT
    ADD FOREIGN KEY (IDLOGEMENT) REFERENCES LOGEMENT (ID);

ALTER TABLE AVIS
    ADD FOREIGN KEY (IDLOGEMENT) REFERENCES LOGEMENT (ID);

ALTER TABLE INDISPONIBILITE
    ADD FOREIGN KEY (IDLOGEMENT) REFERENCES LOGEMENT (ID);

ALTER TABLE RESPECTER
    ADD FOREIGN KEY (IDLOGEMENT) REFERENCES LOGEMENT (ID);

ALTER TABLE RESPECTER
    ADD FOREIGN KEY (IDREGLESLOGEMENT) REFERENCES ReglesLogement (ID);

ALTER TABLE CONTENIR
    ADD FOREIGN KEY (IDLOGEMENT) REFERENCES LOGEMENT (ID);

ALTER TABLE CONTENIR
    ADD FOREIGN KEY (IDAMENAGEMENT) REFERENCES AMENAGEMENT (ID);

ALTER TABLE NOTIFICATION
    ADD FOREIGN KEY (IDUSER) REFERENCES UTILISATEUR (ID);

ALTER TABLE FACTURE
    ADD FOREIGN KEY (IDPROPRIETAIRE) REFERENCES PROPRIETAIRE (IDUSER);