DELETE FROM RESPECTER;
DELETE FROM CONTENIR;
DELETE FROM NOTIFICATION;
DELETE FROM INDISPONIBILITE;
DELETE FROM RESERVATION;
DELETE FROM REGLESLOGEMENT;
DELETE FROM AMENAGEMENT;
DELETE FROM IMAGELOGEMENT;
DELETE FROM DEPENSE;
DELETE FROM FACTURE;

DELETE FROM LOGEMENT;
ALTER TABLE LOGEMENT AUTO_INCREMENT = 1;

DELETE FROM TYPELOGEMENT;
ALTER TABLE TYPELOGEMENT AUTO_INCREMENT = 1;

DELETE FROM REGLESLOGEMENT;
ALTER TABLE REGLESLOGEMENT AUTO_INCREMENT = 1;

ALTER TABLE CATEGORIEAMENAGEMENT AUTO_INCREMENT = 1;

ALTER TABLE AMENAGEMENT AUTO_INCREMENT = 1;

ALTER TABLE NOTIFICATION AUTO_INCREMENT = 1;

ALTER TABLE IMAGELOGEMENT AUTO_INCREMENT = 1;

ALTER TABLE DEPENSE AUTO_INCREMENT = 1;

DELETE FROM ICONE;
ALTER TABLE ICONE AUTO_INCREMENT = 1;

DELETE FROM PROPRIETAIRE;
DELETE FROM ADMINISTRATEUR;
DELETE FROM UTILISATEUR;
ALTER TABLE UTILISATEUR AUTO_INCREMENT = 1;