name: 'Deployment'

on:
  push:
    branches:
      - prod
      - master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    
      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile_back
          push: true
          tags: tayarim-project/tayarim_back:latest
#      - name: Build the Docker image for the backend
#        run: docker build . -f Dockerfile_back --tag rg.fr-par.scw.cloud/tayarim-registry/backend:$GITHUB_SHA
#      - name: Tag the image
#        run: docker tag rg.fr-par.scw.cloud/tayarim-registry/backend:$GITHUB_SHA rg.fr-par.scw.cloud/tayarim-registry/backend:latest
#      - name: Push the image to private registry
#        run: docker push rg.fr-par.scw.cloud/tayarim-registry/backend:$GITHUB_SHA
#      - name: Push the image with latest tag
#        run: docker push rg.fr-par.scw.cloud/tayarim-registry/backend:latest
#
#  trigger_workflow:
#    runs-on: ubuntu-latest
#    needs:
#      - build-backend-image
#    steps:
#      - name: Trigger terraform workflow
#        uses: convictional/trigger-workflow-and-wait@v1.6.5
#        with:
#          owner: ESGI-project-s-team
#          repo: iac-tayarim
#          github_token: ${{ secrets.ACTIONS_KEY }}
#          workflow_file_name: terraform_deploy.yml
#          ref: main
#          wait_interval: 30
#          propagate_failure: true
#          wait_workflow: true
#          client_payload: '{"back":"${{ github.sha }}"}'
