name: 'Deployment'

on:
  push:
    branches:
      - prod

jobs:
  build-backend-image:
    runs-on: ubuntu-latest
    steps:
    # A MODIFIER
      - uses: actions/checkout@v3
      - name: Docker login to registry
        run: echo "${{ secrets.REGISTRY_PASS }}" | docker login rg.fr-par.scw.cloud/babyteacher-regitstry -u nologin --password-stdin
      - name: Build the Docker image for the backend
        run: docker build . -f Dockerfile_back --tag rg.fr-par.scw.cloud/babyteacher-registry/backend:$GITHUB_SHA
      - name: Tag the image
        run: docker tag rg.fr-par.scw.cloud/babyteacher-registry/backend:$GITHUB_SHA rg.fr-par.scw.cloud/babyteacher-registry/backend:latest
      - name: Push the image to private registry
        run: docker push rg.fr-par.scw.cloud/babyteacher-registry/backend:$GITHUB_SHA
      - name: Push the image with latest tag
        run: docker push rg.fr-par.scw.cloud/babyteacher-registry/backend:latest
